### ISSUE TITLE
Crash when try to open turret with " Turret Control Unit "

### ISSUE THREAD

**Issue by Corleone91** [SanAndreasP/SanLib#6]
Game is crash when try to open turret with "Turret Control Unit" in MP

  Minecraft version: 12.2.2
        Forge version: 14.23.5.2859
       Sanlib version:  1.6.3
TurretMod version: 4.0.0-beta.4.6

\/ \/ \/  Crash Log  \/ \/ \/

---- Minecraft Crash Report ----
// Don't do that.

Time: 8/31/22 5:55 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.nbt.NBTUtil.func_180708_a(SourceFile:77)
	at de.sanandrew.mods.turretmod.client.gui.tcu.page.PlayerHeads.getRandomSkull(PlayerHeads.java:66)
	at de.sanandrew.mods.turretmod.registry.turret.GuiTcuRegistry$Page.getIcon(GuiTcuRegistry.java:217)
	at de.sanandrew.mods.turretmod.client.gui.element.tcu.nav.ButtonNav.bakeData(ButtonNav.java:54)
	at de.sanandrew.mods.turretmod.client.gui.element.tcu.nav.PageNavigation.bakeData(PageNavigation.java:44)
	at de.sanandrew.mods.sanlib.lib.client.gui.GuiDefinition.lambda$initGui$0(GuiDefinition.java:171)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at de.sanandrew.mods.sanlib.lib.client.gui.GuiDefinition.initGui(GuiDefinition.java:173)
	at de.sanandrew.mods.turretmod.client.util.GuiHelper.initGuiDef(GuiHelper.java:16)
	at de.sanandrew.mods.turretmod.client.gui.tcu.GuiTcuScreen.func_73866_w_(GuiTcuScreen.java:64)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018)
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:501)
	at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:322)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:112)
	at de.sanandrew.mods.turretmod.init.CommonProxy.openGui(CommonProxy.java:141)
	at de.sanandrew.mods.turretmod.client.init.ClientProxy.openGui(ClientProxy.java:184)
	at de.sanandrew.mods.turretmod.util.TmrUtils.openGui(TmrUtils.java:45)
	at de.sanandrew.mods.turretmod.entity.turret.EntityTurret.func_184645_a(EntityTurret.java:362)
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1227)
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187097_a(PlayerControllerMP.java:549)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1567)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.nbt.NBTUtil.func_180708_a(SourceFile:77)
	at de.sanandrew.mods.turretmod.client.gui.tcu.page.PlayerHeads.getRandomSkull(PlayerHeads.java:66)
	at de.sanandrew.mods.turretmod.registry.turret.GuiTcuRegistry$Page.getIcon(GuiTcuRegistry.java:217)
	at de.sanandrew.mods.turretmod.client.gui.element.tcu.nav.ButtonNav.bakeData(ButtonNav.java:54)
	at de.sanandrew.mods.turretmod.client.gui.element.tcu.nav.PageNavigation.bakeData(PageNavigation.java:44)
	at de.sanandrew.mods.sanlib.lib.client.gui.GuiDefinition.lambda$initGui$0(GuiDefinition.java:171)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at de.sanandrew.mods.sanlib.lib.client.gui.GuiDefinition.initGui(GuiDefinition.java:173)
	at de.sanandrew.mods.turretmod.client.util.GuiHelper.initGuiDef(GuiHelper.java:16)
	at de.sanandrew.mods.turretmod.client.gui.tcu.GuiTcuScreen.func_73866_w_(GuiTcuScreen.java:64)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018)
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:501)
	at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:322)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:112)
	at de.sanandrew.mods.turretmod.init.CommonProxy.openGui(CommonProxy.java:141)
	at de.sanandrew.mods.turretmod.client.init.ClientProxy.openGui(ClientProxy.java:184)
	at de.sanandrew.mods.turretmod.util.TmrUtils.openGui(TmrUtils.java:45)
	at de.sanandrew.mods.turretmod.entity.turret.EntityTurret.func_184645_a(EntityTurret.java:362)
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1227)
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187097_a(PlayerControllerMP.java:549)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1567)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Muricann'/1586, l='MpServer', x=150.40, y=69.00, z=245.91]]
	Chunk stats: MultiplayerChunkCache: 729, 729
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (148,64,248), Chunk: (at 4,4,8 in 9,15; contains blocks 144,0,240 to 159,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 385 game time, 385 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 91 total; [EntitySkeleton['Скелет'/4106, l='MpServer', x=122.50, y=28.00, z=322.50], EntitySkeleton['Скелет'/4107, l='MpServer', x=122.50, y=28.00, z=321.50], EntitySkeleton['Скелет'/4108, l='MpServer', x=123.50, y=28.00, z=324.50], EntityRabbit['Кролик'/69, l='MpServer', x=71.50, y=64.00, z=290.50], EntityZombie['Зомби'/4169, l='MpServer', x=189.45, y=28.00, z=175.21], EntityZombie['Зомби'/4170, l='MpServer', x=196.50, y=33.00, z=177.50], EntitySkeleton['Скелет'/4171, l='MpServer', x=194.30, y=33.00, z=176.35], EntityRabbit['Кролик'/96, l='MpServer', x=129.50, y=69.00, z=195.50], EntityRabbit['Кролик'/97, l='MpServer', x=131.50, y=72.00, z=198.50], EntityRabbit['Кролик'/98, l='MpServer', x=124.50, y=65.00, z=189.50], EntityRabbit['Кролик'/99, l='MpServer', x=116.72, y=64.00, z=188.50], EntityRabbit['Кролик'/100, l='MpServer', x=122.50, y=65.00, z=190.50], EntityHorse['Лошадь'/111, l='MpServer', x=171.81, y=68.00, z=207.48], EntityHorse['Лошадь'/112, l='MpServer', x=170.73, y=68.00, z=207.50], EntitySheep['Овца'/113, l='MpServer', x=181.50, y=72.00, z=275.50], EntitySheep['Овца'/114, l='MpServer', x=181.50, y=72.00, z=275.50], EntitySheep['Овца'/115, l='MpServer', x=181.50, y=72.00, z=272.50], EntitySheep['Овца'/116, l='MpServer', x=177.50, y=72.00, z=272.50], EntityZombie['Зомби'/4216, l='MpServer', x=143.50, y=19.00, z=248.50], EntityCow['Корова'/121, l='MpServer', x=191.50, y=71.00, z=268.50], EntitySkeleton['Скелет'/4217, l='MpServer', x=142.50, y=19.00, z=250.50], EntityCow['Корова'/122, l='MpServer', x=193.50, y=72.00, z=267.50], EntityCow['Корова'/123, l='MpServer', x=191.50, y=71.00, z=265.50], EntityCow['Корова'/124, l='MpServer', x=191.50, y=71.00, z=265.50], EntityCow['Корова'/125, l='MpServer', x=198.17, y=70.00, z=295.56], EntityCow['Корова'/126, l='MpServer', x=197.50, y=69.00, z=299.50], EntityCow['Корова'/127, l='MpServer', x=195.45, y=70.00, z=298.06], EntityCow['Корова'/128, l='MpServer', x=198.01, y=70.00, z=296.72], EntityHorse['Лошадь'/134, l='MpServer', x=201.50, y=69.00, z=204.50], EntityHorse['Лошадь'/135, l='MpServer', x=210.96, y=68.00, z=204.67], EntityHorse['Лошадь'/136, l='MpServer', x=207.50, y=67.00, z=201.50], EntityHorse['Лошадь'/137, l='MpServer', x=202.00, y=68.00, z=211.85], EntityHorse['Лошадь'/139, l='MpServer', x=200.50, y=69.00, z=206.50], EntityCow['Корова'/144, l='MpServer', x=227.50, y=63.00, z=236.50], EntityCow['Корова'/145, l='MpServer', x=227.50, y=63.00, z=236.50], EntityCow['Корова'/146, l='MpServer', x=225.33, y=63.00, z=232.90], EntitySheep['Овца'/147, l='MpServer', x=224.45, y=62.18, z=229.45], EntitySheep['Овца'/148, l='MpServer', x=220.55, y=62.28, z=235.96], EntityZombie['Зомби'/4270, l='MpServer', x=200.50, y=50.00, z=187.50], EntityZombie['Зомби'/4271, l='MpServer', x=200.50, y=50.00, z=186.50], EntitySkeleton['Скелет'/4319, l='MpServer', x=117.50, y=29.00, z=294.50], EntitySkeleton['Скелет'/4320, l='MpServer', x=118.50, y=29.00, z=294.50], EntitySkeleton['Скелет'/4321, l='MpServer', x=117.50, y=29.00, z=293.50], EntitySkeleton['Скелет'/4322, l='MpServer', x=116.50, y=29.00, z=293.50], EntityZombie['Зомби'/4370, l='MpServer', x=215.50, y=55.00, z=186.50], EntityCreeper['Крипер'/4387, l='MpServer', x=185.50, y=30.00, z=196.50], EntityCreeper['Крипер'/4388, l='MpServer', x=190.22, y=32.00, z=187.58], EntityCreeper['Крипер'/4389, l='MpServer', x=188.46, y=31.00, z=203.19], EntitySkeleton['Скелет'/4406, l='MpServer', x=91.50, y=21.00, z=299.50], EntityCreeper['Крипер'/4605, l='MpServer', x=119.50, y=41.00, z=192.50], EntitySpider['Паук'/4643, l='MpServer', x=115.50, y=29.00, z=293.50], EntityCreeper['Крипер'/4644, l='MpServer', x=122.50, y=29.00, z=296.50], EntitySkeleton['Скелет'/4661, l='MpServer', x=225.50, y=14.00, z=274.50], EntitySkeleton['Скелет'/4662, l='MpServer', x=223.50, y=14.00, z=272.50], EntitySkeleton['Скелет'/4663, l='MpServer', x=224.50, y=14.00, z=273.50], EntitySkeleton['Скелет'/4720, l='MpServer', x=108.50, y=20.00, z=169.50], EntitySkeleton['Скелет'/4721, l='MpServer', x=111.50, y=20.00, z=168.50], EntitySkeleton['Скелет'/4806, l='MpServer', x=140.50, y=36.00, z=259.50], EntityCreeper['Крипер'/4828, l='MpServer', x=92.50, y=28.00, z=324.50], EntityCreeper['Крипер'/4829, l='MpServer', x=92.50, y=28.00, z=323.50], EntitySkeleton['Скелет'/4834, l='MpServer', x=124.50, y=40.00, z=295.50], EntityItem['item.item.leather'/4836, l='MpServer', x=205.40, y=66.00, z=204.43], EntityCreeper['Крипер'/4839, l='MpServer', x=147.50, y=15.00, z=260.50], EntityCreeper['Крипер'/4840, l='MpServer', x=146.50, y=15.00, z=257.50], EntityTurret['Revolver Turret (T2)'/4869, l='MpServer', x=150.50, y=69.00, z=248.50], EntitySkeleton['Скелет'/3151, l='MpServer', x=118.50, y=14.00, z=173.50], EntitySkeleton['Скелет'/3228, l='MpServer', x=175.32, y=45.00, z=237.53], EntityBat['Летучая мышь'/3241, l='MpServer', x=155.87, y=14.69, z=262.51], EntityBat['Летучая мышь'/3242, l='MpServer', x=162.08, y=17.55, z=260.31], EntitySkeleton['Скелет'/3572, l='MpServer', x=166.50, y=25.00, z=180.50], EntityBat['Летучая мышь'/3589, l='MpServer', x=116.98, y=44.00, z=316.26], EntitySkeleton['Скелет'/3604, l='MpServer', x=224.50, y=12.00, z=281.50], EntitySkeleton['Скелет'/3605, l='MpServer', x=223.50, y=12.00, z=279.50], EntityBat['Летучая мышь'/3636, l='MpServer', x=216.53, y=54.00, z=187.63], EntityBat['Летучая мышь'/3637, l='MpServer', x=225.39, y=16.09, z=307.36], EntityBat['Летучая мышь'/3638, l='MpServer', x=125.27, y=41.01, z=266.99], EntitySkeleton['Скелет'/3691, l='MpServer', x=123.50, y=40.00, z=292.50], EntitySpider['Паук'/3692, l='MpServer', x=165.50, y=15.00, z=253.50], EntityBat['Летучая мышь'/3727, l='MpServer', x=136.61, y=11.89, z=198.33], EntityPlayerSP['Muricann'/1586, l='MpServer', x=150.40, y=69.00, z=245.91], EntitySkeleton['Скелет'/3784, l='MpServer', x=130.50, y=21.00, z=278.50], EntityBat['Летучая мышь'/3811, l='MpServer', x=119.16, y=30.96, z=167.56], EntityZombie['Зомби'/1772, l='MpServer', x=180.50, y=29.00, z=176.50], EntityZombie['Зомби'/3848, l='MpServer', x=137.54, y=34.00, z=256.75], EntityBat['Летучая мышь'/3849, l='MpServer', x=93.98, y=30.82, z=178.50], EntityBat['Летучая мышь'/3878, l='MpServer', x=162.36, y=14.73, z=258.64], EntityBat['Летучая мышь'/3879, l='MpServer', x=160.96, y=17.96, z=255.57], EntityBat['Летучая мышь'/3880, l='MpServer', x=161.03, y=18.08, z=251.34], EntityBat['Летучая мышь'/3881, l='MpServer', x=167.77, y=16.40, z=254.96], EntityZombieVillager['Зомби-крестьянин'/4020, l='MpServer', x=148.50, y=20.00, z=310.50], EntitySkeleton['Скелет'/4027, l='MpServer', x=128.50, y=16.00, z=312.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_341, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4310642864 bytes (4110 MB) / 5281480704 bytes (5036 MB) up to 6355222528 bytes (6060 MB)
	JVM Flags: 14 total; -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=300M -XX:+UseFastAccessorMethods -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:MaxGCPauseMillis=100 -XX:-DisableExplicitGC -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:SoftRefLRUPolicyMSPerMB=5 -XX:MaxGCPauseMillis=50 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms5120m -Xmx6144m
	IntCache: cache: 0, tcache: 9, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version        | Source                                  | Signature                                |
	|:------ |:-------------- |:-------------- |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2         | minecraft.jar                           | None                                     |
	| LCHIJA | mcp            | 9.42           | minecraft.jar                           | None                                     |
	| LCHIJA | FML            | 8.0.99.99      | forge-1.12.2-14.23.5.2859-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge          | 14.23.5.2859   | forge-1.12.2-14.23.5.2859-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | jei            | 4.16.1.302     | jei_1.12.2-4.16.1.302.jar               | None                                     |
	| LCHIJA | sanlib         | 1.6.3          | SanLib-1.12.2-1.6.3.jar                 | 4aad6d31d04fd4b54ac08427561b110ee66198fd |
	| LCHIJA | sanplayermodel | 1.2.2          | SanLib-1.12.2-1.6.3.jar                 | None                                     |
	| LCHIJA | sapturretmod   | 4.0.0-beta.4.6 | TurretMod-1.12-4.0.0-beta.4.6.jar       | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.78' Renderer: 'NVIDIA GeForce RTX 2070 Super/PCIe/SSE2'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 2070 Super/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.78, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

**Comment by SanAndreaP** [comment]
Just cleaning up :)
Also wrong mod.

PS: The 1.12.2 version of the Turret Mod is not maintained anymore and the current iteration for 1.16 (unreleased, as of writing this) has this problem fixed.
